error message :

case1 : Xlib.error.DisplayConnectionError
solve : 
	xhost +

case2 : ptrace.error.PtraceError
solve :
	sudo bash
	echo 0 > /proc/sys/kernel/yama/ptrace_scope

case3 : mkdir permission denied
solve : 
	sudo chattr log/
	sudo lsattr log/
	sudo chmod -R 777 log/

python learner.py --actor-num 15 --load-model 191115120712

Xvfb :15 &
export DISPLAY=:15
DISPLAY=:15 python actor.py --simnum 14 --load-model 191115120712

ps aux 
kill -9 pid

export WINEDEBUG=-all